language: python

sudo: false

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

notifications:
  email:
    recipients:
      - dchudz@gmail.com
    on_success: change
    on_failure: always

# Setup anaconda
before_install:
  # (via https://gist.github.com/dan-blanchard/7045057)
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pystan patsy multipledispatch pandas nose scikit-learn
  - python setup.py install
  - which nosetests
  - which python

# Run test
script:
  - nosetests bayesglm/tests
